<?php

  $teams = array(
    'bucks' => array(
      'name' => 'Milwaukee Bucks',
      'primary color' => '#00471B',
      'secondary color' => '#EEE1C6',
      'logo' => 'logos/bucks.png',
      'conference' => 'eastern',
      'division' => 'central',
    ),
    'mavericks' => array(
      'name' => 'Dallas Mavericks',
      'primary color' => '#00538C',
      'secondary color' => '#B8C4CA',
      'logo' => 'logos/mavericks.png',
      'conference' => 'western',
      'division' => 'southwest',
    ),
    'rockets' => array(
      'name' => 'Houston Rockets',
      'primary color' => '#000000',
      'secondary color' => '#CE1141',
      'logo' => 'logos/rockets.png',
      'conference' => 'western',
      'division' => 'southwest',
    ),
    'grizzlies' => array(
      'name' => 'Memphis Grizzlies',
      'primary color' => '#12173F',
      'secondary color' => '#5D76A9',
      'logo' => 'logos/grizzlies.png',
      'conference' => 'western',
      'division' => 'southwest',
    ),
    'pelicans' => array(
      'name' => 'New Orleans Pelicans',
      'primary color' => '#0C2340',
      'secondary color' => '#C8102E',
      'logo' => 'logos/pelicans.png',
      'conference' => 'western',
      'division' => 'southwest',
      'division' => '',
    ),
    'spurs' => array(
      'name' => 'San Antonio Spurs',
      'primary color' => '#000000',
      'secondary color' => '#C4CED4',
      'logo' => 'logos/spurs.png',
      'conference' => 'western',
      'division' => 'southwest',
    ),
    'nuggets' => array(
      'name' => 'Denver Nuggets',
      'primary color' => '#0E2240',
      'secondary color' => '#FEC524',
      'logo' => 'logos/nuggets.png',
      'conference' => 'western',
      'division' => 'northwest',
    ),
    'timberwolves' => array(
      'name' => 'Minnesota Timberwolves',
      'primary color' => '#0C2340',
      'secondary color' => '#9EA2A2',
      'logo' => 'logos/timerwolves.png',
      'conference' => 'western',
      'division' => 'northwest',
    ),
    'thunder' => array(
      'name' => 'Oklahoma City Thunder',
      'primary color' => '#EF3B24',
      'secondary color' => '#007AC1',
      'logo' => 'logos/thunder.png',
      'conference' => 'western',
      'division' => 'northwest',
    ),
    'blazers' => array(
      'name' => 'Portland Trail Blazers',
      'primary color' => '#000000',
      'secondary color' => '#E03A3E',
      'logo' => 'logos/blazers.png',
      'conference' => 'western',
      'division' => 'northwest',
    ),
    'jazz' => array(
      'name' => 'Utah Jazz',
      'primary color' => '#002B5C',
      'secondary color' => '#F9A01B',
      'logo' => 'logos/jazz.png',
      'conference' => 'western',
      'division' => 'northwest',
    ),
    'warriors' => array(
      'name' => 'Golden State Warriors',
      'primary color' => '#006BB6',
      'secondary color' => '#FDB927',
      'logo' => 'logos/warriors.png',
      'conference' => 'western',
      'division' => 'pacific',
    ),
    'clippers' => array(
      'name' => 'Los Angeles Clippers',
      'primary color' => '#C8102E',
      'secondary color' => '#1D42BA',
      'logo' => 'logos/clippers.png',
      'conference' => 'western',
      'division' => 'pacific',
    ),
    'lakers' => array(
      'name' => 'Los Angeles Lakers',
      'primary color' => '#FDB927',
      'secondary color' => '#552583',
      'logo' => 'logos/lakers.png',
      'conference' => 'western',
      'division' => 'pacific',
    ),
    'sixers' => array(
      'name' => 'Philadelphia 76ers',
      'primary color' => '#006BB6',
      'secondary color' => '#ED174C',
      'logo' => 'logos/sixers.png',
      'conference' => 'eastern',
      'division' => 'atlantic',
    ),
    'knicks' => array(
      'name' => 'New York Knicks',
      'primary color' => '#006BB6',
      'secondary color' => '#F58426',
      'logo' => 'logos/knicks.png',
      'conference' => 'eastern',
      'division' => 'atlantic',
    ),
    'nets' => array(
      'name' => 'Brooklyn Nets',
      'primary color' => '#000000',
      'secondary color' => '#FFFFFF',
      'logo' => 'logos/nets.png',
      'conference' => 'eastern',
      'division' => 'atlantic',
    ),
    'celtics' => array(
      'name' => 'Boston Celtics',
      'primary color' => '#007A33',
      'secondary color' => '#BA9653',
      'logo' => 'logos/celtics.png',
      'conference' => 'eastern',
      'division' => 'atlantic',
    ),
    'kings' => array(
      'name' => 'Sacramento Kings',
      'primary color' => '#5A2D81',
      'secondary color' => '#63727A',
      'logo' => 'logos/kings.png',
      'conference' => 'western',
      'division' => 'pacific',
    ),
    'suns' => array(
      'name' => 'Phoenix Suns',
      'primary color' => '#1D1160',
      'secondary color' => '#E56020',
      'logo' => 'logos/suns.png',
      'conference' => 'western',
      'division' => 'pacific',
    ),
    'raptors' => array(
      'name' => 'Toronto Raptors',
      'primary color' => '#CE1141',
      'secondary color' => '#A1A1A4',
      'logo' => 'logos/raptors.png',
      'conference' => 'eastern',
      'division' => 'atlantic',
    ),
    'bulls' => array(
      'name' => 'Chicago Bulls',
      'primary color' => '#000000',
      'secondary color' => '#CE1141',
      'logo' => 'logos/bulls.png',
      'conference' => 'eastern',
      'division' => 'central',
    ),
    'cavaliers' => array(
      'name' => 'Cleveland Cavaliers',
      'primary color' => '#041E42',
      'secondary color' => '#FFB81C',
      'logo' => 'logos/cavaliers.png',
      'conference' => 'eastern',
      'division' => 'central',
    ),
    'pistons' => array(
      'name' => 'Detroit Pistons',
      'primary color' => '#C8102E',
      'secondary color' => '#006BB6',
      'logo' => 'logos/pistons.png',
      'conference' => 'eastern',
      'division' => 'central',
    ),
    'pacers' => array(
      'name' => 'Indiana Pacers',
      'primary color' => '#002D62',
      'secondary color' => '#FDBB30',
      'logo' => 'logos/pacers.png',
      'conference' => 'eastern',
      'division' => 'central',
    ),
    'hawks' => array(
      'name' => 'Atlanta Hawks',
      'primary color' => '#E03A3E',
      'secondary color' => '#FFFFFF',
      'logo' => 'logos/hawks.png',
      'conference' => 'eastern',
      'division' => 'southeast',
    ),
    'hornets' => array(
      'name' => 'Charlotte Hornets',
      'primary color' => '#1D1160',
      'secondary color' => '#00788C',
      'logo' => 'logos/hornets.png',
      'conference' => 'eastern',
      'division' => 'southeast',
    ),
    'heat' => array(
      'name' => 'Miami Heat',
      'primary color' => '#98002E',
      'secondary color' => '#F9A01B',
      'logo' => 'logos/heat.png',
      'conference' => 'eastern',
      'division' => 'southeast',
    ),
    'magic' => array(
      'name' => 'Orlando Magic',
      'primary color' => '#0077C0',
      'secondary color' => '#C4CED4',
      'logo' => 'logos/magic.png',
      'conference' => 'eastern',
      'division' => 'southeast',
    ),
    'wizards' => array(
      'name' => 'Washington Wizards',
      'primary color' => '#002B5C',
      'secondary color' => '#E31837',
      'logo' => 'logos/wizards.png',
      'conference' => 'eastern',
      'division' => 'southeast',
    ),
  );

